from __future__ import annotations

from datetime import date, datetime


SUPPORTED_LANGUAGES = ("en", "de", "fr")


CATALOG: dict[str, dict[str, str]] = {
    "en": {
        "condition.clear": "Clear",
        "condition.partly_cloudy": "Partly Cloudy",
        "condition.cloudy": "Cloudy",
        "condition.fog": "Fog",
        "condition.showers": "Showers",
        "condition.sleet": "Sleet",
        "condition.rain": "Rain",
        "condition.snow": "Snow",
        "condition.thunderstorm": "Thunderstorm",
        "condition.thundersnow": "Thundersnow",
        "weather.steady": "STEADY WEATHER",
        "weather.rain_likely": "RAIN LIKELY",
        "weather.storm_risk": "STORM RISK",
        "weather.cold_and_wet": "COLD AND WET",
        "weather.warmer_later": "WARMER LATER",
        "weather.cold_morning": "COLD MORNING",
        "weather.dry_all_day": "DRY ALL DAY",
        "weather.bring_coat": "BRING A COAT",
        "weather.bring_umbrella": "BRING UMBRELLA",
        "weather.mild_afternoon": "MILD AFTERNOON",
        "schedule.free_all_day": "FREE ALL DAY",
        "schedule.free_all_morning": "FREE ALL MORNING",
        "schedule.free_after": "FREE AFTER {time}",
        "schedule.enjoy": "ENJOY!",
        "schedule.no_timed_events": "NO TIMED EVENTS",
        "schedule.light_day": "LIGHT DAY",
        "detail.title_today": "Today",
        "detail.title_tomorrow": "Tomorrow",
        "weather.fact_feels": "FEELS {value}°",
        "weather.fact_rain": "RAIN {value}%",
        "weather.fact_wind": "WIND {value} {unit}",
        "weather.fact_low_feels": "LOW FEELS {value}°",
        "weather.fact_high": "HIGH {value}°",
        "weather.fact_low": "LOW {value}°",
        "status.calendar_fallback": "CALENDAR ISSUE - USING SAMPLE DATA",
        "status.weather_fallback": "WEATHER ISSUE - USING SAMPLE DATA",
        "status.updated_at": "Updated {weekday} {month_day}, {year} {time}",
        "insight.rain_likely": "Rain likely {subject}.",
        "insight.storm_risk": "Storm risk {subject}.",
        "insight.snow_expected": "Snow expected {subject}.",
        "insight.wintry_mix": "Wintry mix possible {subject}.",
        "insight.windy_conditions": "Windy conditions {subject}.",
        "insight.low_visibility": "Low visibility {subject}.",
        "insight.cold_morning_warmer_later": "Cold morning, warmer later.",
        "insight.cool_through_day": "Cool conditions through the day.",
        "insight.clear_steady": "Clear and steady conditions.",
        "insight.conditions": "{condition} conditions {subject}.",
        "insight.next_event": "Next: {title} at {time}",
        "insight.first_event": "First event: {title} at {time}",
        "insight.all_day": "All-day: {title}",
        "subject.today": "today",
        "subject.tomorrow": "tomorrow",
        "ui.title": "Inky Planner Config",
        "ui.eyebrow": "Inky Planner",
        "ui.settings": "Settings",
        "ui.hero": "Configure the planner, test your data sources, and tune privacy-mode slideshow behavior from one appliance-friendly control surface.",
        "ui.device": "Device",
        "ui.open_locally": "Open locally at",
        "ui.planner_basics": "Planner Basics",
        "ui.general": "General",
        "ui.dashboard_title": "Dashboard Title",
        "ui.language": "Language",
        "ui.lang.en": "English",
        "ui.lang.de": "German",
        "ui.lang.fr": "French",
        "ui.weather": "Weather",
        "ui.location": "Location",
        "ui.city_state_country": "City / State / Province",
        "ui.country_code": "Country Code",
        "ui.temp_unit": "Temperature Unit",
        "ui.unit.fahrenheit": "Fahrenheit",
        "ui.unit.celsius": "Celsius",
        "ui.find_location_matches": "Find Location Matches",
        "ui.resolved_coordinates": "Resolved Coordinates",
        "ui.timezone": "Timezone",
        "ui.advanced_weather": "Advanced Weather Options",
        "ui.thundersnow_f": "Thundersnow Threshold (F)",
        "ui.thundersnow_c": "Thundersnow Threshold (C)",
        "ui.snow_temp_f": "Snow Temp Threshold (F)",
        "ui.snow_temp_c": "Snow Temp Threshold (C)",
        "ui.recent_snow_hours": "Recent Snow Window (Hours)",
        "ui.recent_snow_mm": "Recent Snow Threshold (mm)",
        "ui.recent_snow_mm_15": "Minutely Snow Threshold (mm)",
        "ui.recent_precip_minutes": "Recent Precip Window (Minutes)",
        "ui.recent_precip_mm": "Recent Precip Threshold (mm)",
        "ui.calendar_setup": "Calendar Setup",
        "ui.feeds": "Feeds",
        "ui.enabled": "Enabled",
        "ui.draft": "Draft",
        "ui.feed_url": "Feed URL",
        "ui.feed_url_placeholder": "Paste a calendar feed URL",
        "ui.provider": "Provider",
        "ui.ics_feed": "ICS Feed",
        "ui.label": "Label",
        "ui.calendar_label": "Calendar Label",
        "ui.test_this_feed": "Test This Feed",
        "ui.connected": "Connected",
        "ui.problem": "Problem",
        "ui.loaded_events": "loaded {count} event(s).",
        "ui.new_calendar_feed": "New Calendar Feed",
        "ui.new_label": "New label",
        "ui.add_another_feed": "Add Another Feed",
        "ui.google_help_copy": "Use the secret iCal address for the exact calendar you want on the display.",
        "ui.apple_help_copy": "Use a published or shared iCalendar link for the chosen calendar.",
        "ui.outlook_help_copy": "Publish the calendar, then paste the ICS subscription link into a new card.",
        "ui.google_help": "Google help",
        "ui.apple_help": "Apple help",
        "ui.outlook_help": "Outlook help",
        "ui.privacy_mode": "Privacy Mode",
        "ui.photos": "Photos",
        "ui.upload_photos": "Upload Photos",
        "ui.delete_all": "Delete All",
        "ui.photo_upload_help": "Choose one or more images to add them to the slideshow.",
        "ui.current_photos": "Current Photos",
        "ui.uploaded_count": "{count} uploaded",
        "ui.slideshow": "Slideshow",
        "ui.every_seconds": "Every {seconds} seconds",
        "ui.shuffled_suffix": ", shuffled",
        "ui.photo_folder": "Photo Folder",
        "ui.slide_interval_seconds": "Slide Interval (Seconds)",
        "ui.shuffle_slideshow": "Shuffle Slideshow",
        "ui.shuffle_order": "Shuffle order",
        "ui.delete": "Delete",
        "ui.no_uploaded_photos": "No Uploaded Photos Yet",
        "ui.photo_empty_help": "Photo mode will keep using the sample image until you add your own library.",
        "ui.page_of": "Page {page} of {total}",
        "ui.previous": "Previous",
        "ui.next": "Next",
        "ui.location_matches": "Location Matches",
        "ui.pick_correct_place": "Pick the correct place",
        "ui.use_this_location": "Use This Location",
        "ui.feedback": "Feedback",
        "ui.results": "Results",
        "ui.calendar_test_results": "Calendar Test Results",
        "ui.action_bar": "Action Bar",
        "ui.save_changes": "Save Changes",
        "ui.refresh_now": "Refresh Now",
        "ui.test_calendar": "Test Calendar",
        "ui.test_weather": "Test Weather",
        "ui.export_settings": "Export Settings",
        "ui.import_settings": "Import Settings",
        "ui.help.save_changes": "saves your settings and updates the Inky display.",
        "ui.help.refresh_now": "redraws the current screen using your saved settings.",
        "ui.help.test_calendar": "checks your calendar feeds and previews upcoming events.",
        "ui.help.test_weather": "checks weather loading for the saved location.",
        "ui.help.import_export": "backs up your current config or restores a validated settings file.",
        "ui.message.settings_saved": "Settings saved. Hardware refresh requested.",
        "ui.message.refresh_requested": "Hardware refresh requested. The screen should update within a few seconds.",
        "ui.message.calendar_ok": "Calendar OK: loaded {count} day(s). Review the feed previews below.",
        "ui.message.feed_status": "{label}: {status}. Review the feed preview below.",
        "ui.message.weather_ok": "Weather OK: loaded {count} day(s).",
        "ui.message.geocode_found": "Found {count} location match(es). Choose one below.",
        "ui.message.location_selected": "Location selected: {display_name} ({latitude:.4f}, {longitude:.4f}). Click Save Changes to refresh the display.",
        "ui.message.photo_uploaded": "Uploaded {count} photo(s). Click Save Changes to refresh the display.",
        "ui.message.photo_deleted": "Deleted {name}. Click Save Changes to refresh the display.",
        "ui.message.photo_deleted_all": "Deleted {count} photo(s). Click Save Changes to refresh the display.",
        "ui.message.import_success": "Settings imported successfully. Previous settings backed up to {name}. Click Save Changes or Refresh Now to update the display.",
        "ui.error.save_settings": "Could not save settings: {error}",
        "ui.error.refresh": "Refresh failed: {error}",
        "ui.error.calendar_test": "Calendar test failed: {error}",
        "ui.error.calendar_feed_missing": "That calendar feed could not be found for testing.",
        "ui.error.calendar_feed_test": "Calendar feed test failed: {error}",
        "ui.error.weather_test": "Weather test failed: {error}",
        "ui.error.location_lookup": "Location lookup failed: {error}",
        "ui.error.apply_location": "Could not apply location: {error}",
        "ui.error.no_photo_upload": "No supported image files were uploaded.",
        "ui.error.photo_upload": "Photo upload failed: {error}",
        "ui.error.photo_delete": "Photo delete failed: {error}",
        "ui.error.photo_delete_one": "Could not delete that photo.",
        "ui.error.photo_delete_all": "Bulk photo delete failed: {error}",
        "ui.error.photo_none_to_delete": "No photos were available to delete.",
        "ui.error.photo_page": "Could not change photo page: {error}",
        "ui.error.import_choose_file": "Choose a settings JSON file to import.",
        "ui.error.import_failed": "Settings import failed: {error}",
        "ui.status.ok": "OK",
    },
    "de": {
        "condition.clear": "Klar",
        "condition.partly_cloudy": "Teilweise bewölkt",
        "condition.cloudy": "Bewölkt",
        "condition.fog": "Nebel",
        "condition.showers": "Schauer",
        "condition.sleet": "Schneeregen",
        "condition.rain": "Regen",
        "condition.snow": "Schnee",
        "condition.thunderstorm": "Gewitter",
        "condition.thundersnow": "Gewitterschnee",
        "weather.steady": "BESTÄNDIGES WETTER",
        "weather.rain_likely": "REGEN WAHRSCHEINLICH",
        "weather.storm_risk": "GEWITTERRISIKO",
        "weather.cold_and_wet": "KALT UND NASS",
        "weather.warmer_later": "SPÄTER WÄRMER",
        "weather.cold_morning": "KALTER MORGEN",
        "weather.dry_all_day": "DEN GANZEN TAG TROCKEN",
        "weather.bring_coat": "JACKE MITNEHMEN",
        "weather.bring_umbrella": "REGENSCHIRM MITNEHMEN",
        "weather.mild_afternoon": "MILDER NACHMITTAG",
        "schedule.free_all_day": "DEN GANZEN TAG FREI",
        "schedule.free_all_morning": "DEN GANZEN VORMITTAG FREI",
        "schedule.free_after": "FREI AB {time}",
        "schedule.enjoy": "VIEL SPASS!",
        "schedule.no_timed_events": "KEINE TERMINE",
        "schedule.light_day": "RUHIGER TAG",
        "detail.title_today": "Heute",
        "detail.title_tomorrow": "Morgen",
        "weather.fact_feels": "GEFÜHLT {value}°",
        "weather.fact_rain": "REGEN {value}%",
        "weather.fact_wind": "WIND {value} {unit}",
        "weather.fact_low_feels": "TIEF GEFÜHLT {value}°",
        "weather.fact_high": "HOCH {value}°",
        "weather.fact_low": "TIEF {value}°",
        "status.calendar_fallback": "KALENDERPROBLEM - BEISPIELDATEN AKTIV",
        "status.weather_fallback": "WETTERPROBLEM - BEISPIELDATEN AKTIV",
        "status.updated_at": "Aktualisiert {weekday} {month_day} {year}, {time}",
        "insight.rain_likely": "Wahrscheinlich Regen {subject}.",
        "insight.storm_risk": "Gewitterrisiko {subject}.",
        "insight.snow_expected": "Schnee erwartet {subject}.",
        "insight.wintry_mix": "Winterlicher Mix möglich {subject}.",
        "insight.windy_conditions": "Windige Bedingungen {subject}.",
        "insight.low_visibility": "Geringe Sicht {subject}.",
        "insight.cold_morning_warmer_later": "Kalter Morgen, später wärmer.",
        "insight.cool_through_day": "Kühl über den ganzen Tag.",
        "insight.clear_steady": "Klar und beständig.",
        "insight.conditions": "{condition}e Bedingungen {subject}.",
        "insight.next_event": "Nächster Termin: {title} um {time}",
        "insight.first_event": "Erster Termin: {title} um {time}",
        "insight.all_day": "Ganztägig: {title}",
        "subject.today": "heute",
        "subject.tomorrow": "morgen",
        "ui.title": "Inky Planner Konfiguration",
        "ui.eyebrow": "Inky Planner",
        "ui.settings": "Einstellungen",
        "ui.hero": "Konfiguriere den Planer, prüfe deine Datenquellen und passe den Diashow-Modus für Privatsphäre über eine gerätefreundliche Oberfläche an.",
        "ui.device": "Gerät",
        "ui.open_locally": "Lokal öffnen unter",
        "ui.planner_basics": "Planer-Grundlagen",
        "ui.general": "Allgemein",
        "ui.dashboard_title": "Dashboard-Titel",
        "ui.language": "Sprache",
        "ui.lang.en": "Englisch",
        "ui.lang.de": "Deutsch",
        "ui.lang.fr": "Französisch",
        "ui.weather": "Wetter",
        "ui.location": "Ort",
        "ui.city_state_country": "Stadt / Region / Land",
        "ui.country_code": "Ländercode",
        "ui.temp_unit": "Temperatureinheit",
        "ui.unit.fahrenheit": "Fahrenheit",
        "ui.unit.celsius": "Celsius",
        "ui.find_location_matches": "Ortsvorschläge finden",
        "ui.resolved_coordinates": "Aufgelöste Koordinaten",
        "ui.timezone": "Zeitzone",
        "ui.advanced_weather": "Erweiterte Wetteroptionen",
        "ui.thundersnow_f": "Schwelle Gewitterschnee (F)",
        "ui.thundersnow_c": "Schwelle Gewitterschnee (C)",
        "ui.snow_temp_f": "Schneetemperatur-Schwelle (F)",
        "ui.snow_temp_c": "Schneetemperatur-Schwelle (C)",
        "ui.recent_snow_hours": "Zeitfenster für Schnee (Stunden)",
        "ui.recent_snow_mm": "Schwelle für Schnee (mm)",
        "ui.recent_snow_mm_15": "Minütliche Schneeschwelle (mm)",
        "ui.recent_precip_minutes": "Zeitfenster für Niederschlag (Minuten)",
        "ui.recent_precip_mm": "Schwelle für Niederschlag (mm)",
        "ui.calendar_setup": "Kalender-Setup",
        "ui.feeds": "Feeds",
        "ui.enabled": "Aktiv",
        "ui.draft": "Entwurf",
        "ui.feed_url": "Feed-URL",
        "ui.feed_url_placeholder": "URL des Kalender-Feeds einfügen",
        "ui.provider": "Anbieter",
        "ui.ics_feed": "ICS-Feed",
        "ui.label": "Bezeichnung",
        "ui.calendar_label": "Kalendername",
        "ui.test_this_feed": "Diesen Feed testen",
        "ui.connected": "Verbunden",
        "ui.problem": "Problem",
        "ui.loaded_events": "{count} Ereignis(se) geladen.",
        "ui.new_calendar_feed": "Neuer Kalender-Feed",
        "ui.new_label": "Neue Bezeichnung",
        "ui.add_another_feed": "Weiteren Feed hinzufügen",
        "ui.google_help_copy": "Nutze die geheime iCal-Adresse für genau den Kalender, der angezeigt werden soll.",
        "ui.apple_help_copy": "Nutze einen veröffentlichten oder geteilten iCalendar-Link für den gewünschten Kalender.",
        "ui.outlook_help_copy": "Veröffentliche den Kalender und füge dann den ICS-Abolink in eine neue Karte ein.",
        "ui.google_help": "Google-Hilfe",
        "ui.apple_help": "Apple-Hilfe",
        "ui.outlook_help": "Outlook-Hilfe",
        "ui.privacy_mode": "Privatmodus",
        "ui.photos": "Fotos",
        "ui.upload_photos": "Fotos hochladen",
        "ui.delete_all": "Alle löschen",
        "ui.photo_upload_help": "Wähle ein oder mehrere Bilder aus, um sie zur Diashow hinzuzufügen.",
        "ui.current_photos": "Aktuelle Fotos",
        "ui.uploaded_count": "{count} hochgeladen",
        "ui.slideshow": "Diashow",
        "ui.every_seconds": "Alle {seconds} Sekunden",
        "ui.shuffled_suffix": ", zufällig",
        "ui.photo_folder": "Fotoordner",
        "ui.slide_interval_seconds": "Wechselintervall (Sekunden)",
        "ui.shuffle_slideshow": "Diashow mischen",
        "ui.shuffle_order": "Zufällige Reihenfolge",
        "ui.delete": "Löschen",
        "ui.no_uploaded_photos": "Noch keine Fotos hochgeladen",
        "ui.photo_empty_help": "Der Fotomodus nutzt weiter das Beispielbild, bis du eigene Bilder hinzufügst.",
        "ui.page_of": "Seite {page} von {total}",
        "ui.previous": "Zurück",
        "ui.next": "Weiter",
        "ui.location_matches": "Ortsvorschläge",
        "ui.pick_correct_place": "Den richtigen Ort auswählen",
        "ui.use_this_location": "Diesen Ort verwenden",
        "ui.feedback": "Rückmeldung",
        "ui.results": "Ergebnisse",
        "ui.calendar_test_results": "Kalender-Testergebnisse",
        "ui.action_bar": "Aktionsleiste",
        "ui.save_changes": "Änderungen speichern",
        "ui.refresh_now": "Jetzt aktualisieren",
        "ui.test_calendar": "Kalender testen",
        "ui.test_weather": "Wetter testen",
        "ui.export_settings": "Einstellungen exportieren",
        "ui.import_settings": "Einstellungen importieren",
        "ui.help.save_changes": "speichert deine Einstellungen und aktualisiert das Inky-Display.",
        "ui.help.refresh_now": "zeichnet den aktuellen Bildschirm mit deinen gespeicherten Einstellungen neu.",
        "ui.help.test_calendar": "prüft deine Kalender-Feeds und zeigt kommende Ereignisse an.",
        "ui.help.test_weather": "prüft das Laden der Wetterdaten für den gespeicherten Ort.",
        "ui.help.import_export": "sichert deine aktuelle Konfiguration oder stellt eine validierte Einstellungsdatei wieder her.",
        "ui.message.settings_saved": "Einstellungen gespeichert. Hardware-Aktualisierung angefordert.",
        "ui.message.refresh_requested": "Hardware-Aktualisierung angefordert. Der Bildschirm sollte sich in wenigen Sekunden aktualisieren.",
        "ui.message.calendar_ok": "Kalender OK: {count} Tag(e) geladen. Prüfe die Feed-Vorschau unten.",
        "ui.message.feed_status": "{label}: {status}. Prüfe die Feed-Vorschau unten.",
        "ui.message.weather_ok": "Wetter OK: {count} Tag(e) geladen.",
        "ui.message.geocode_found": "{count} Ortsvorschläge gefunden. Wähle unten einen aus.",
        "ui.message.location_selected": "Ort gewählt: {display_name} ({latitude:.4f}, {longitude:.4f}). Klicke auf Änderungen speichern, um das Display zu aktualisieren.",
        "ui.message.photo_uploaded": "{count} Foto(s) hochgeladen. Klicke auf Änderungen speichern, um das Display zu aktualisieren.",
        "ui.message.photo_deleted": "{name} gelöscht. Klicke auf Änderungen speichern, um das Display zu aktualisieren.",
        "ui.message.photo_deleted_all": "{count} Foto(s) gelöscht. Klicke auf Änderungen speichern, um das Display zu aktualisieren.",
        "ui.message.import_success": "Einstellungen erfolgreich importiert. Die vorherige Konfiguration wurde als {name} gesichert. Klicke auf Änderungen speichern oder Jetzt aktualisieren, um das Display zu aktualisieren.",
        "ui.error.save_settings": "Einstellungen konnten nicht gespeichert werden: {error}",
        "ui.error.refresh": "Aktualisierung fehlgeschlagen: {error}",
        "ui.error.calendar_test": "Kalendertest fehlgeschlagen: {error}",
        "ui.error.calendar_feed_missing": "Dieser Kalender-Feed wurde für den Test nicht gefunden.",
        "ui.error.calendar_feed_test": "Kalender-Feed-Test fehlgeschlagen: {error}",
        "ui.error.weather_test": "Wettertest fehlgeschlagen: {error}",
        "ui.error.location_lookup": "Ortssuche fehlgeschlagen: {error}",
        "ui.error.apply_location": "Ort konnte nicht übernommen werden: {error}",
        "ui.error.no_photo_upload": "Es wurden keine unterstützten Bilddateien hochgeladen.",
        "ui.error.photo_upload": "Foto-Upload fehlgeschlagen: {error}",
        "ui.error.photo_delete": "Foto konnte nicht gelöscht werden: {error}",
        "ui.error.photo_delete_one": "Dieses Foto konnte nicht gelöscht werden.",
        "ui.error.photo_delete_all": "Löschen aller Fotos fehlgeschlagen: {error}",
        "ui.error.photo_none_to_delete": "Es waren keine Fotos zum Löschen vorhanden.",
        "ui.error.photo_page": "Fotoseite konnte nicht gewechselt werden: {error}",
        "ui.error.import_choose_file": "Wähle eine JSON-Datei mit Einstellungen zum Importieren aus.",
        "ui.error.import_failed": "Import der Einstellungen fehlgeschlagen: {error}",
        "ui.status.ok": "OK",
    },
    "fr": {
        "condition.clear": "Dégagé",
        "condition.partly_cloudy": "Partiellement nuageux",
        "condition.cloudy": "Nuageux",
        "condition.fog": "Brouillard",
        "condition.showers": "Averses",
        "condition.sleet": "Neige fondue",
        "condition.rain": "Pluie",
        "condition.snow": "Neige",
        "condition.thunderstorm": "Orage",
        "condition.thundersnow": "Orage de neige",
        "weather.steady": "TEMPS STABLE",
        "weather.rain_likely": "PLUIE PROBABLE",
        "weather.storm_risk": "RISQUE D'ORAGE",
        "weather.cold_and_wet": "FROID ET HUMIDE",
        "weather.warmer_later": "PLUS DOUX PLUS TARD",
        "weather.cold_morning": "MATIN FROID",
        "weather.dry_all_day": "SEC TOUTE LA JOURNÉE",
        "weather.bring_coat": "PRENDS UN MANTEAU",
        "weather.bring_umbrella": "PRENDS UN PARAPLUIE",
        "weather.mild_afternoon": "APRÈS-MIDI DOUX",
        "schedule.free_all_day": "LIBRE TOUTE LA JOURNÉE",
        "schedule.free_all_morning": "LIBRE TOUTE LA MATINÉE",
        "schedule.free_after": "LIBRE APRÈS {time}",
        "schedule.enjoy": "PROFITE !",
        "schedule.no_timed_events": "AUCUN ÉVÉNEMENT",
        "schedule.light_day": "JOURNÉE LÉGÈRE",
        "detail.title_today": "Aujourd'hui",
        "detail.title_tomorrow": "Demain",
        "weather.fact_feels": "RESSENTI {value}°",
        "weather.fact_rain": "PLUIE {value}%",
        "weather.fact_wind": "VENT {value} {unit}",
        "weather.fact_low_feels": "MIN RESSENTI {value}°",
        "weather.fact_high": "MAX {value}°",
        "weather.fact_low": "MIN {value}°",
        "status.calendar_fallback": "PROBLÈME DE CALENDRIER - DONNÉES D'EXEMPLE ACTIVES",
        "status.weather_fallback": "PROBLÈME MÉTÉO - DONNÉES D'EXEMPLE ACTIVES",
        "status.updated_at": "Mis à jour {weekday} {month_day} {year} à {time}",
        "insight.rain_likely": "Pluie probable {subject}.",
        "insight.storm_risk": "Risque d'orage {subject}.",
        "insight.snow_expected": "Neige attendue {subject}.",
        "insight.wintry_mix": "Mélange hivernal possible {subject}.",
        "insight.windy_conditions": "Conditions venteuses {subject}.",
        "insight.low_visibility": "Faible visibilité {subject}.",
        "insight.cold_morning_warmer_later": "Matin froid, plus doux plus tard.",
        "insight.cool_through_day": "Temps frais toute la journée.",
        "insight.clear_steady": "Temps clair et stable.",
        "insight.conditions": "Conditions {condition} {subject}.",
        "insight.next_event": "Prochain: {title} à {time}",
        "insight.first_event": "Premier événement: {title} à {time}",
        "insight.all_day": "Toute la journée: {title}",
        "subject.today": "aujourd'hui",
        "subject.tomorrow": "demain",
        "ui.title": "Configuration Inky Planner",
        "ui.eyebrow": "Inky Planner",
        "ui.settings": "Réglages",
        "ui.hero": "Configurez le planificateur, testez vos sources de données et ajustez le diaporama du mode confidentialité depuis une seule interface adaptée à l'appareil.",
        "ui.device": "Appareil",
        "ui.open_locally": "Ouvrir localement à",
        "ui.planner_basics": "Bases du planificateur",
        "ui.general": "Général",
        "ui.dashboard_title": "Titre du tableau de bord",
        "ui.language": "Langue",
        "ui.lang.en": "Anglais",
        "ui.lang.de": "Allemand",
        "ui.lang.fr": "Français",
        "ui.weather": "Météo",
        "ui.location": "Lieu",
        "ui.city_state_country": "Ville / Région / Pays",
        "ui.country_code": "Code pays",
        "ui.temp_unit": "Unité de température",
        "ui.unit.fahrenheit": "Fahrenheit",
        "ui.unit.celsius": "Celsius",
        "ui.find_location_matches": "Trouver des lieux",
        "ui.resolved_coordinates": "Coordonnées résolues",
        "ui.timezone": "Fuseau horaire",
        "ui.advanced_weather": "Options météo avancées",
        "ui.thundersnow_f": "Seuil d'orage de neige (F)",
        "ui.thundersnow_c": "Seuil d'orage de neige (C)",
        "ui.snow_temp_f": "Seuil de neige (F)",
        "ui.snow_temp_c": "Seuil de neige (C)",
        "ui.recent_snow_hours": "Fenêtre de neige récente (heures)",
        "ui.recent_snow_mm": "Seuil de neige récente (mm)",
        "ui.recent_snow_mm_15": "Seuil minute neige (mm)",
        "ui.recent_precip_minutes": "Fenêtre de précipitation récente (minutes)",
        "ui.recent_precip_mm": "Seuil de précipitation récente (mm)",
        "ui.calendar_setup": "Configuration du calendrier",
        "ui.feeds": "Flux",
        "ui.enabled": "Activé",
        "ui.draft": "Brouillon",
        "ui.feed_url": "URL du flux",
        "ui.feed_url_placeholder": "Collez l'URL du flux calendrier",
        "ui.provider": "Fournisseur",
        "ui.ics_feed": "Flux ICS",
        "ui.label": "Libellé",
        "ui.calendar_label": "Libellé du calendrier",
        "ui.test_this_feed": "Tester ce flux",
        "ui.connected": "Connecté",
        "ui.problem": "Problème",
        "ui.loaded_events": "{count} événement(s) chargés.",
        "ui.new_calendar_feed": "Nouveau flux calendrier",
        "ui.new_label": "Nouveau libellé",
        "ui.add_another_feed": "Ajouter un autre flux",
        "ui.google_help_copy": "Utilisez l'adresse iCal secrète du calendrier exact à afficher.",
        "ui.apple_help_copy": "Utilisez un lien iCalendar publié ou partagé pour le calendrier choisi.",
        "ui.outlook_help_copy": "Publiez le calendrier puis collez le lien d'abonnement ICS dans une nouvelle carte.",
        "ui.google_help": "Aide Google",
        "ui.apple_help": "Aide Apple",
        "ui.outlook_help": "Aide Outlook",
        "ui.privacy_mode": "Mode confidentialité",
        "ui.photos": "Photos",
        "ui.upload_photos": "Importer des photos",
        "ui.delete_all": "Tout supprimer",
        "ui.photo_upload_help": "Choisissez une ou plusieurs images pour les ajouter au diaporama.",
        "ui.current_photos": "Photos actuelles",
        "ui.uploaded_count": "{count} importée(s)",
        "ui.slideshow": "Diaporama",
        "ui.every_seconds": "Toutes les {seconds} secondes",
        "ui.shuffled_suffix": ", aléatoire",
        "ui.photo_folder": "Dossier photo",
        "ui.slide_interval_seconds": "Intervalle (secondes)",
        "ui.shuffle_slideshow": "Diaporama aléatoire",
        "ui.shuffle_order": "Ordre aléatoire",
        "ui.delete": "Supprimer",
        "ui.no_uploaded_photos": "Aucune photo importée",
        "ui.photo_empty_help": "Le mode photo continuera d'utiliser l'image d'exemple jusqu'à ce que vous ajoutiez votre propre bibliothèque.",
        "ui.page_of": "Page {page} sur {total}",
        "ui.previous": "Précédent",
        "ui.next": "Suivant",
        "ui.location_matches": "Lieux trouvés",
        "ui.pick_correct_place": "Choisissez le bon lieu",
        "ui.use_this_location": "Utiliser ce lieu",
        "ui.feedback": "Retour",
        "ui.results": "Résultats",
        "ui.calendar_test_results": "Résultats du test calendrier",
        "ui.action_bar": "Barre d'actions",
        "ui.save_changes": "Enregistrer",
        "ui.refresh_now": "Rafraîchir",
        "ui.test_calendar": "Tester le calendrier",
        "ui.test_weather": "Tester la météo",
        "ui.export_settings": "Exporter les réglages",
        "ui.import_settings": "Importer les réglages",
        "ui.help.save_changes": "enregistre vos réglages et met à jour l'écran Inky.",
        "ui.help.refresh_now": "redessine l'écran actuel avec vos réglages enregistrés.",
        "ui.help.test_calendar": "vérifie vos flux de calendrier et prévisualise les événements à venir.",
        "ui.help.test_weather": "vérifie le chargement météo pour le lieu enregistré.",
        "ui.help.import_export": "sauvegarde votre configuration actuelle ou restaure un fichier de réglages validé.",
        "ui.message.settings_saved": "Réglages enregistrés. Actualisation matérielle demandée.",
        "ui.message.refresh_requested": "Actualisation matérielle demandée. L'écran devrait se mettre à jour dans quelques secondes.",
        "ui.message.calendar_ok": "Calendrier OK : {count} jour(s) chargé(s). Consultez l'aperçu des flux ci-dessous.",
        "ui.message.feed_status": "{label} : {status}. Consultez l'aperçu du flux ci-dessous.",
        "ui.message.weather_ok": "Météo OK : {count} jour(s) chargé(s).",
        "ui.message.geocode_found": "{count} correspondance(s) trouvée(s). Choisissez-en une ci-dessous.",
        "ui.message.location_selected": "Lieu sélectionné : {display_name} ({latitude:.4f}, {longitude:.4f}). Cliquez sur Enregistrer pour actualiser l'écran.",
        "ui.message.photo_uploaded": "{count} photo(s) importée(s). Cliquez sur Enregistrer pour actualiser l'écran.",
        "ui.message.photo_deleted": "{name} supprimé. Cliquez sur Enregistrer pour actualiser l'écran.",
        "ui.message.photo_deleted_all": "{count} photo(s) supprimée(s). Cliquez sur Enregistrer pour actualiser l'écran.",
        "ui.message.import_success": "Réglages importés avec succès. La configuration précédente a été sauvegardée sous {name}. Cliquez sur Enregistrer ou Rafraîchir pour mettre à jour l'écran.",
        "ui.error.save_settings": "Impossible d'enregistrer les réglages : {error}",
        "ui.error.refresh": "Rafraîchissement impossible : {error}",
        "ui.error.calendar_test": "Échec du test calendrier : {error}",
        "ui.error.calendar_feed_missing": "Ce flux calendrier est introuvable pour le test.",
        "ui.error.calendar_feed_test": "Échec du test du flux calendrier : {error}",
        "ui.error.weather_test": "Échec du test météo : {error}",
        "ui.error.location_lookup": "Échec de la recherche du lieu : {error}",
        "ui.error.apply_location": "Impossible d'appliquer ce lieu : {error}",
        "ui.error.no_photo_upload": "Aucun fichier image pris en charge n'a été importé.",
        "ui.error.photo_upload": "Échec de l'import photo : {error}",
        "ui.error.photo_delete": "Échec de la suppression photo : {error}",
        "ui.error.photo_delete_one": "Impossible de supprimer cette photo.",
        "ui.error.photo_delete_all": "Échec de la suppression complète des photos : {error}",
        "ui.error.photo_none_to_delete": "Aucune photo à supprimer.",
        "ui.error.photo_page": "Impossible de changer de page photo : {error}",
        "ui.error.import_choose_file": "Choisissez un fichier JSON de réglages à importer.",
        "ui.error.import_failed": "Échec de l'import des réglages : {error}",
        "ui.status.ok": "OK",
    },
}

DAY_ABBREVIATIONS = {
    "en": ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
    "de": ["Mo", "Di", "Mi", "Do", "Fr", "Sa", "So"],
    "fr": ["Lun", "Mar", "Mer", "Jeu", "Ven", "Sam", "Dim"],
}

MONTH_ABBREVIATIONS = {
    "en": ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
    "de": ["Jan", "Feb", "Mär", "Apr", "Mai", "Jun", "Jul", "Aug", "Sep", "Okt", "Nov", "Dez"],
    "fr": ["janv.", "févr.", "mars", "avr.", "mai", "juin", "juil.", "août", "sept.", "oct.", "nov.", "déc."],
}


def translate(language: str, key: str, **kwargs) -> str:
    catalog = CATALOG.get(language) or CATALOG["en"]
    template = catalog.get(key) or CATALOG["en"].get(key) or key
    return template.format(**kwargs)


def weekday_abbrev(value: date | datetime, language: str) -> str:
    labels = DAY_ABBREVIATIONS.get(language) or DAY_ABBREVIATIONS["en"]
    return labels[value.weekday()]


def month_day(value: date | datetime, language: str) -> str:
    months = MONTH_ABBREVIATIONS.get(language) or MONTH_ABBREVIATIONS["en"]
    return f"{months[value.month - 1]} {value.day}"


def format_clock(value: datetime, language: str) -> str:
    if language == "en":
        return value.strftime("%-I:%M %p")
    return value.strftime("%H:%M")


def format_updated_at(value: datetime, language: str) -> str:
    return translate(
        language,
        "status.updated_at",
        weekday=weekday_abbrev(value, language),
        month_day=month_day(value, language),
        year=value.year,
        time=format_clock(value, language),
    )
